# Generated by Django 6.0 on 2025-12-26 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='學生姓名')),
                ('reason', models.TextField(verbose_name='申請事由')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登記時間')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登記人')),
            ],
        ),
    ]
